In [1]:
import numpy as np

In [5]:
# Exercise 1: Create a 4X2 integer array and Prints its attributes
# The shape of an array.
# Array dimensions.
# The Length of each element of the array in bytes.

arr = np.random.randint(1, 10, size= (4,2))
print(arr)
print(f"\nshape: {arr.shape}")
print(f"dimensions: {arr.ndim}")
print(f"length of each element: {arr.itemsize}")

[[9 5]
 [7 9]
 [3 7]
 [9 5]]

shape: (4, 2)
dimensions: 2
length of each element: 8


In [7]:
# Exercise 2: Create a 5X2 integer array from a range between 100 to 200
# such that the difference between each element is 10

print(np.arange(100, 200, 10).reshape(5,2))

[[100 110]
 [120 130]
 [140 150]
 [160 170]
 [180 190]]


In [9]:
# Exercise 3: Following is the provided numPy array.
# eturn array of items by taking the third column from all rows

arr = np.array([[11 ,22, 33], [44, 55, 66], [77, 88, 99]])

print(f"array: \n{arr}\n")
print(f"third column: {arr[:,2]}")

array: 
[[11 22 33]
 [44 55 66]
 [77 88 99]]

third column: [33 66 99]


In [14]:
# Exercise 4: Return array of odd rows and even columns from below numpy array

arr = np.array([[3 ,6, 9, 12],
                [15 ,18, 21, 24],
                [27 ,30, 33, 36],
                [39 ,42, 45, 48],
                [51 ,54, 57, 60]])

res = arr[0::2,1::2]

print(f"array: \n{arr}\n")
print(f"result: \n{res}")

array: 
[[ 3  6  9 12]
 [15 18 21 24]
 [27 30 33 36]
 [39 42 45 48]
 [51 54 57 60]]

result: 
[[ 6 12]
 [30 36]
 [54 60]]


In [16]:
# Exercise 5: Create a result array by adding the following two NumPy arrays.
# Next, modify the result array by calculating the square of each element

arr1 = np.array([[5, 6, 9], [21 ,18, 27]])
arr2 = np.array([[15 ,33, 24], [4 ,7, 1]])

adding = arr1 + arr2
print(f"addition of two arrays is \n{adding}\n")

sqr = adding ** 2
print(f"square root of all elements \n{sqr}")

addition of two arrays is 
[[20 39 33]
 [25 25 28]]

square root of all elements 
[[ 400 1521 1089]
 [ 625  625  784]]


In [19]:
# Exercise 6: Split the array into four equal-sized sub-arrays
# 8X3 integer array from a range between 10 to 34, difference between each element is 1

arr = np.arange(10,34).reshape(8,3)

print(f"array: \n{arr}\n")

print(np.split(arr, 4))

array: 
[[10 11 12]
 [13 14 15]
 [16 17 18]
 [19 20 21]
 [22 23 24]
 [25 26 27]
 [28 29 30]
 [31 32 33]]

[array([[10, 11, 12],
       [13, 14, 15]]), array([[16, 17, 18],
       [19, 20, 21]]), array([[22, 23, 24],
       [25, 26, 27]]), array([[28, 29, 30],
       [31, 32, 33]])]


In [21]:
# Exercise 7: Sort following NumPy array
# by the second row
# by the second column

arr = np.array([[34,43,73],[82,22,12],[53,94,66]])

print(f"original: \n{arr}\n")

row = arr[:,arr[1,:].argsort()]
print(f"Sorting Original array by secoond row: \n{row}\n")

col = arr[arr[:,1].argsort()]
print(f"Sorting Original array by secoond column: \n{col}\n")

original: 
[[34 43 73]
 [82 22 12]
 [53 94 66]]

Sorting Original array by secoond row: 
[[73 43 34]
 [12 22 82]
 [66 94 53]]

Sorting Original array by secoond column: 
[[82 22 12]
 [34 43 73]
 [53 94 66]]



In [22]:
# Exercise 8: Print max from axis 0 and min from axis 1 from the following 2-D array.

arr = np.array([[34,43,73],
                [82,22,12],
                [53,94,66]])

print(f"original: \n{arr}\n")

print(f"max from axis 0: {arr.max(axis= 0)}")
print(f"min from axis 1: {arr.min(axis= 1)}")

original: 
[[34 43 73]
 [82 22 12]
 [53 94 66]]

max from axis 0: [82 94 73]
min from axis 1: [34 12 53]


In [25]:
# Exercise 9: Delete the second column from a given array and insert the following new column in its place.

arr = np.array([[34,43,73],
                [82,22,12],
                [53,94,66]])
new_col = np.array([[10,10,10]])

print(f"original: \n{arr}\n")
new_arr = np.delete(arr, 1, axis= 1)
print(f"delete second col: \n{new_arr}\n")
result = np.insert(arr, 1, new_col, axis= 1)
print(f"inset new col: \n{result}\n")

original: 
[[34 43 73]
 [82 22 12]
 [53 94 66]]

delete second col: 
[[34 73]
 [82 12]
 [53 66]]

inset new col: 
[[34 10 43 73]
 [82 10 22 12]
 [53 10 94 66]]

